services:
  web:
    build: .
    env_file: .env
    environment:
      DJANGO_DATABASE_PATH: /data/db.sqlite3
    ports:
      - "8000:8000"
    volumes:
      - data:/data
    command: sh -c "python manage.py migrate --noinput && gunicorn deadliner.wsgi --bind 0.0.0.0:8000"

volumes:
  data:
