# Generated by Django 5.2.17 on 2026-08-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('completed', 'Concluído')], default='active', max_length=9),
        ),
    ]
