# Generated by Django 5.2.17 on 2026-08-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_service_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="description",
            new_name="notes",
        ),
        migrations.AlterField(
            model_name="service",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
