# Generated by Django 5.2.17 on 2026-08-28 22:24
"""Bootstrap the catalogue with the declaration of foundation section 3.2.

This is a bootstrap and never the source of truth: once it has run, the catalogue is edited
through the administration site (specs/adr/0005-service-catalogue.md).
"""

from django.db import migrations

CATALOGUE = (
    (
        "Regularização e Licenciamento",
        (
            "Licenciamentos Ambientais",
            "Cadastro Ambiental Rural (CAR)",
            "Corte de Árvores Nativas (CANI)",
            "Regularização Fundiária",
            "Ratificação: Faixa de Fronteira",
            "Outorga de Recursos Hídricos",
        ),
    ),
    (
        "Geotecnologias",
        (
            "Georreferenciamento",
            "Sensoriamento Remoto",
            "Agricultura de Precisão",
            "Projetos de Drenagem",
        ),
    ),
    (
        "Sustentabilidade e ESG",
        (
            "Diagnóstico Global ESG",
            "Inventário de GEE",
            "Levantamento de Estoque de Carbono",
            "Planos de Descarbonização",
            "Geração de Créditos de Carbono",
        ),
    ),
)


def seed_the_catalogue(apps, schema_editor):
    ServiceCategory = apps.get_model("core", "ServiceCategory")
    CatalogService = apps.get_model("core", "CatalogService")
    for category_position, (category_name, service_names) in enumerate(CATALOGUE, start=1):
        category = ServiceCategory.objects.create(
            name=category_name, position=category_position
        )
        CatalogService.objects.bulk_create(
            [
                CatalogService(category=category, name=name, position=position)
                for position, name in enumerate(service_names, start=1)
            ]
        )


def remove_the_seeded_catalogue(apps, schema_editor):
    ServiceCategory = apps.get_model("core", "ServiceCategory")
    CatalogService = apps.get_model("core", "CatalogService")
    for category_name, service_names in CATALOGUE:
        CatalogService.objects.filter(
            category__name=category_name, name__in=service_names
        ).delete()
    ServiceCategory.objects.filter(
        name__in=[category_name for category_name, _ in CATALOGUE]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_the_service_catalogue"),
    ]

    operations = [
        migrations.RunPython(seed_the_catalogue, remove_the_seeded_catalogue),
    ]
