# Generated by Django 5.2.17 on 2026-08-28 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_seed_the_declared_catalogue"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="catalog_service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="core.catalogservice",
            ),
        ),
    ]
