# Generated by Django 5.2.17 on 2026-08-28 22:25
"""Point every existing record at the catalogue entry its free text named, and delete the rest.

Step 4 of specs/adr/0005-service-catalogue.md, which authorises the deletion for exactly one
reason: no production database exists, so every row on any disk today is development seed data.
If B11 ships before this merges, this migration is wrong and the owner supplies a mapping. It is
irreversible: a deleted row cannot be brought back by running the migration backwards.
"""

from django.db import migrations


def map_or_delete(apps, schema_editor):
    Service = apps.get_model("core", "Service")
    CatalogService = apps.get_model("core", "CatalogService")
    for entry in CatalogService.objects.all():
        Service.objects.filter(notes=entry.name).update(catalog_service=entry)
    Service.objects.filter(catalog_service__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_the_service_names_its_catalogue_entry"),
    ]

    operations = [
        migrations.RunPython(map_or_delete),
    ]
