# Generated by Django 5.2.17 on 2026-08-28 22:30
"""Bootstrap the two people who enter most records (foundation section 6).

The list grows through the form, which mints a row for any name nobody anticipated
(specs/adr/0006-submitter-identity.md). The key is computed by the same pure function the form
resolves through, because two spellings of one key would be two people.
"""

from django.db import migrations

from core.identity import normalize_person_name

KNOWN_SUBMITTERS = ("José Victor", "Geovanna")


def seed_the_known_submitters(apps, schema_editor):
    Submitter = apps.get_model("core", "Submitter")
    Submitter.objects.bulk_create(
        [
            Submitter(display_name=name, normalized_name=normalize_person_name(name))
            for name in KNOWN_SUBMITTERS
        ]
    )


def remove_the_seeded_submitters(apps, schema_editor):
    Submitter = apps.get_model("core", "Submitter")
    Submitter.objects.filter(
        normalized_name__in=[normalize_person_name(name) for name in KNOWN_SUBMITTERS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_the_submitter"),
    ]

    operations = [
        migrations.RunPython(seed_the_known_submitters, remove_the_seeded_submitters),
    ]
