# Generated by Django 5.2.17 on 2026-08-28 22:32
"""Delete every record that predates attribution, because no submitter can be inferred for one.

The submitter becomes required here, and a record written before the field existed names nobody.
Guessing one would put a real person's name on records they may not have entered, which is worse
than an empty development table: the audit trail exists to answer who entered this (I6), and an
invented answer is not one.

It stands on the same ground step 4 of specs/adr/0005-service-catalogue.md stands on: no
production database exists, so every row on any disk today is development seed data. If B11 ships
before this merges, this migration is wrong and the owner supplies the attribution. It is
irreversible.
"""

from django.db import migrations


def delete_the_unattributed(apps, schema_editor):
    Service = apps.get_model("core", "Service")
    Service.objects.filter(submitter__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_the_service_names_who_registered_it"),
    ]

    operations = [
        migrations.RunPython(delete_the_unattributed),
    ]
