# Generated by Django 5.2.17 on 2026-08-28 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_attribute_or_delete_unattributed_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="submitter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="core.submitter",
            ),
        ),
    ]
