# Generated by Django 5.2.17 on 2026-08-31 15:04

"""Add the two the deadline is derived from, nullable, so the backfill can fill them.

Step 1 of the owner decision of 2026-08-31. ``due_date`` stays a stored column and stops
being editable, because it is now computed on every write from the two added here.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_every_service_names_who_registered_it"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="term_days",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="due_date",
            field=models.DateField(editable=False),
        ),
    ]
