# Generated by Django 5.2.17 on 2026-08-31 15:06
"""Give every existing record a start date and a term that reproduce the deadline it already has.

Step 2 of the owner decision of 2026-08-31. The start date becomes the stored due date and the
term becomes zero, so the derivation of step 3 computes the same day back and no alert row
changes, no warning re fires and none is lost (I1, I3). It deletes nothing: a row that cannot be
mapped would be a finding to report, and here there is no such row because every service carries
a due date.
"""

from django.db import migrations
from django.db.models import F


def reproduce_each_stored_due_date(apps, schema_editor):
    Service = apps.get_model("core", "Service")
    # One statement that copies the column into itself, so no date is read into Python, parsed
    # and written back, and none can be reshaped on the way.
    Service.objects.filter(start_date__isnull=True).update(start_date=F("due_date"), term_days=0)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_the_start_date_and_the_term"),
    ]

    operations = [
        migrations.RunPython(
            reproduce_each_stored_due_date,
            # Reversing changes no deadline: step 1 backwards drops the two columns this wrote.
            migrations.RunPython.noop,
        ),
    ]
