# Generated by Django 5.2.17 on 2026-08-31 15:07

"""Close the two columns the backfill filled, so a deadline can never derive from nothing.

Step 3 of the owner decision of 2026-08-31, after step 2 gave every existing row a start date
and a term that reproduce the deadline it already carried.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_backfill_the_start_date_and_the_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="service",
            name="term_days",
            field=models.PositiveIntegerField(),
        ),
    ]
