# Generated by Django 5.2.17 on 2026-08-31 15:35
"""The company stops offering the services under Sustentabilidade e ESG.

Board decision of 2026-08-31, delivered as data because the catalogue is data (foundation section
3.1). Deactivation and never deletion: a deadline already points into this category, both
catalogue foreign keys are PROTECT, and deleting the rows would either fail loudly or take a
tracked deadline with it. Per ADR 0005 an inactive category hides every service under it from the
registration form and hides nothing else, so the records that point at one keep listing, keep
being editable and keep earning their warnings.
"""

from django.db import migrations

RETIRED_CATEGORY = "Sustentabilidade e ESG"


def retire_the_category(apps, schema_editor):
    ServiceCategory = apps.get_model("core", "ServiceCategory")
    ServiceCategory.objects.filter(name=RETIRED_CATEGORY).update(is_active=False)


def offer_the_category_again(apps, schema_editor):
    ServiceCategory = apps.get_model("core", "ServiceCategory")
    ServiceCategory.objects.filter(name=RETIRED_CATEGORY).update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_every_service_has_a_start_date_and_a_term"),
    ]

    operations = [
        migrations.RunPython(retire_the_category, offer_the_category_again),
    ]
