"""
Django settings for deadliner project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from deadliner.config import load_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# The single boundary between this project and its environment (backlog B2). Every value below
# is read from here, and nothing else in the project touches os.environ.
_config = load_config(os.environ)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _config.django.secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _config.django.debug

ALLOWED_HOSTS = list(_config.django.allowed_hosts)

# The business configuration, reached from application code through config.get_config() (I4).
DEADLINER = _config.deadliner


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
]

MIDDLEWARE = [
    # First, so every record written while a request is alive carries its correlation keys
    # (foundation section 8).
    "deadliner.log_context.RequestContextMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # Directly after SecurityMiddleware and before everything else, as WhiteNoise's Django
    # integration guide requires; findings in specs/dependencies.md.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "deadliner.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "deadliner.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / _config.django.database_path,
    }
}

# Where the backup_database command writes its copies, resolved like the database path above: an
# absolute value from the environment wins, a relative one hangs off the project directory.
BACKUP_DIRECTORY = BASE_DIR / _config.django.backup_directory


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# The interface is in Portuguese (foundation section 12); Django's own messages follow.
LANGUAGE_CODE = "pt-br"

TIME_ZONE = _config.deadliner.timezone.key

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Inside the secret path segment, because the health endpoint is the single route outside it
# (foundation section 6). Django prefixes a leading slash at settings load, and WhiteNoise takes
# its serving prefix from this value.
STATIC_URL = f"{_config.deadliner.secret_path_segment}/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

# Compression without the hashed filenames of a manifest: the whole asset set is four brand files
# plus the administration site's own bundle, and a manifest would make every template render
# depend on a collectstatic having run. Reasoning and measurements: specs/dependencies.md.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Logging
# https://docs.djangoproject.com/en/5.2/topics/logging/

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "redact_secret_path": {"()": "deadliner.log_redaction.SecretPathRedactionFilter"},
        "log_context": {"()": "deadliner.log_context.LogContextFilter"},
    },
    "formatters": {
        "json": {"()": "deadliner.log_format.JsonFormatter"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["log_context", "redact_secret_path"],
            "formatter": "json",
        },
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        # Django's own configuration attaches handlers this project does not own to the django
        # logger, and those would write the secret path segment unfiltered (I7).
        "django": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}
